apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: devops-toolkit
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-toolkit
  updatePolicy:
    updateMode: Auto